# Generated by Django 4.0.5 on 2022-07-09 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rarerestapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='rare_user',
        ),
    ]
