# Generated by Django 4.0.5 on 2022-07-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarerestapi', '0002_rename_category_id_post_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rare_user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='rareuser',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='rareuser',
            name='create_on',
            field=models.DateField(auto_now=True),
        ),
    ]
